language: node_js
script: 
  - npm test
  - npm install codecov -g
after_script: 
 - export CODECOV_TOKEN="c06452f9-0f94-4fb1-a509-ed368da7a45d"
 - npm run coverage
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
after_success:
  - codecov